import { Link } from 'react-router-dom';
import Logo from '../components/Logo';

const LAST_UPDATED = 'August 27, 2026';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-bg px-4 py-10 sm:px-6 lg:px-10">
      <div className="mx-auto max-w-3xl">
        <div className="mb-8">
          <Link to="/">
            <Logo />
          </Link>
        </div>

        <div className="mb-8 rounded-lg border border-warning/30 bg-warning/5 px-4 py-3 text-sm text-warning">
          <strong>Template notice:</strong> this is a starting-point terms of service, not legal advice. Replace
          the bracketed placeholders and have a lawyer review it before launching publicly or submitting it to
          TikTok, Google, or Meta for app review.
        </div>

        <h1 className="font-display text-3xl font-semibold text-text-primary">Terms of Service</h1>
        <p className="mt-2 text-sm text-text-secondary">Last updated: {LAST_UPDATED}</p>

        <div className="prose prose-invert mt-8 max-w-none space-y-6 text-sm leading-relaxed text-text-secondary">
          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">1. Acceptance of terms</h2>
            <p>
              By creating an account or using ViralPost, you agree to these Terms and our Privacy Policy. If
              you don&apos;t agree, please don&apos;t use the service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">2. Your account</h2>
            <p>
              You&apos;re responsible for the accuracy of the information you provide and for keeping your
              password confidential. You must be at least the age of majority in your jurisdiction to create an
              account.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">3. Connected platform accounts</h2>
            <p>
              When you connect a TikTok, YouTube, or Instagram account, you authorize ViralPost to publish
              content to that account only at the times and for the content you explicitly schedule. You remain
              solely responsible for the content you generate and publish, and for complying with each
              platform&apos;s own terms of service and community guidelines. You can revoke access at any time
              from Connected Accounts.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">4. Acceptable use</h2>
            <p>You agree not to use ViralPost to:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>Publish content that is illegal, infringing, defamatory, or violates a connected
                platform&apos;s community guidelines.</li>
              <li>Attempt to gain unauthorized access to another user&apos;s account or content.</li>
              <li>Abuse rate limits, scrape the service, or interfere with its normal operation.</li>
              <li>Use AI-generated content to impersonate a real person without their consent, or to spread
                deliberate misinformation.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">5. AI-generated content</h2>
            <p>
              Scripts, captions, and hashtags are generated by a third-party AI model based on the topic you
              provide. We don&apos;t guarantee the accuracy, originality, or performance (&quot;virality&quot;)
              of generated content &mdash; review it before publishing. You&apos;re responsible for the final
              content you choose to post.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">6. Termination</h2>
            <p>
              We may suspend or terminate accounts that violate these Terms. You may stop using ViralPost and
              request account deletion at any time (see Privacy Policy § 5).
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">7. Disclaimer &amp; liability</h2>
            <p>
              ViralPost is provided &quot;as is&quot; without warranties of any kind. We are not liable for
              content published to your connected accounts, actions taken by third-party platforms (including
              account suspension or content removal), or losses arising from your use of the service, to the
              fullest extent permitted by law.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">8. Changes</h2>
            <p>
              We may update these Terms from time to time. Continued use of ViralPost after changes take effect
              constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text-primary">9. Contact</h2>
            <p>Questions about these Terms? Email [legal@yourdomain.com].</p>
          </section>
        </div>
      </div>
    </div>
  );
}
